AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  KarpenterRouter

Globals:
  Function:
    Timeout: 3

Resources:
  KarpenterRouterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref ClusterMappingTable
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref ClusterMappingTable
      - Statement:
        - Sid: SQSSendMessagePolicy
          Effect: Allow
          Action:
          - sqs:SendMessage
          Resource: '*'
      - Statement:
        - Sid: EC2DescribeInstancePolicy
          Effect: Allow
          Action:
          - ec2:DescribeInstances
          Resource: '*'
      Events:
        ScheduledChangeRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.health
              detail-type:
                - AWS Health Event
            DeadLetterConfig:
              Arn: !GetAtt EBRuleDLQ.Arn
        SpotInterruptionRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 Spot Instance Interruption Warning
            DeadLetterConfig:
              Arn: !GetAtt EBRuleDLQ.Arn
        InstanceStateChangeRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 Instance State-change Notification
              detail:
                state:
                  - "anything-but":
                    - "pending"
                    - "running"
            DeadLetterConfig:
              Arn: !GetAtt EBRuleDLQ.Arn
  EBRuleDLQ:
    Type: AWS::SQS::Queue
  ClusterMappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ClusterName
          AttributeType: S
      KeySchema:
        - AttributeName: ClusterName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  KarpenterRouterFunction:
    Description: "Karpenter Router Lambda Function ARN"
    Value: !GetAtt KarpenterRouterFunction.Arn
  ClusterMappingTable:
    Description: "DynamoDB Tables to map EKS cluster to SQS queues"
    Value: !Ref ClusterMappingTable
